name: root
channels:
- conda-forge
dependencies:
- basemap
- cartopy
- gdal
- h5py
- ipython
- iris
- jupyter
- matplotlib
- numpy
- numba
- pandas
- python=3.5
- seaborn
- scipy
- xray
- pip:
  - LatLon23
  - umtools
  - git+https://github.com/dennissergeev/sattools.git
  - git+https://github.com/dennissergeev/faamtools.git
